### ISSUE TITLE
关于填充项与选择项重复问题

### ISSUE THREAD

**Issue by Amz-Zy** [Coder-Yu/SDLib#19]
代码作者您好：
        关于您的shillingmodels代码中，选择项与填充项的选择使用的是np.random.randint()这种方法，可是这种方法得到的序列是会出现重复数据的，关于重复数据您是作何处理的？如果不处理的话填充项与选择项的数量可能会少于设定值，是否使用np.random.sample()这个方法更好？

**Comment by Coder-Yu** [comment]
你好，感谢发现这个问题。因为代码是很多年以前写的，疏于维护，没有注意到这个问题。考虑到候选项目数量很多，填充比例低的话，重复数应该不多。我把这里修改一下。

**Comment by Amz-Zy** [comment]
还有个疑问是为什么在选择采样量时要做一步random.gauss(mu, sigma)操作(mu是采样率与物品总量的乘积即预期的采样数量，sigma为0.1mu)，而不是将预期的采样数量直接作为采样量？

**Comment by Amz-Zy** [comment]
然后如果采样量是均值为mu，标准差为0.1mu的高斯分布的话，是有可能出现采样量大于样本容量的情况的
以bandwagonAttack.py这个代码为例：
hotItems = sorted(self.itemProfile.iteritems(), key=lambda d: len(d[1]), reverse=True)[:int(self.selectedSize * len(self.itemProfile))]
热门项目的样本容量大小为：选择率与物品数量的乘积

mu = int(self.selectedSize * len(self.itemProfile))
sigma = int(0.1 * mu)
markedItemsCount = abs(int(round(random.gauss(mu, sigma))))
markedIndexes = random.sample(range(len(self.hotItems)), markedItemsCount)
mu值大小也是选择率与物品数量的乘积，sigma为0.1mu，当做高斯分布后markedItemsCount有概率大于样本容量，这在做random.sample()时会报错，
或许可以修改为: random.sample(range(len(self.hotItems)), max(markedItemsCount, len(self.hotItems)))

**Comment by Coder-Yu** [comment]
因为是早期代码，加上我实际上并没有在这个方向上做后续工作，代码可能有一些问题。你按你的想法修改就行。这个repo可能不会再维护了。谢谢指出问题

**Comment by Amz-Zy** [comment]
好的，感谢回复，希望这个issue能给后续工作者提供一些帮助
